### ISSUE TITLE
[HS2] ObjectMoveHotkeys doesn't work well

### ISSUE THREAD

**Issue by hahaha12353** [DeathWeasel1337/KK_Plugins#222]
https://github.com/IllusionMods/KK_Plugins/assets/158009099/d367ae23-7799-4245-80f9-94189b7740d1

 Hi! Thanks for your effort, most of all!

 When I play StudioNeo2V in HS2, the Movement controller does not only go wrong with right corner's exta axis, but also it doesn't look the way it should be(has no red, green, blue squares as below's picture).
![trouble](https://github.com/IllusionMods/KK_Plugins/assets/158009099/00f03ba8-6298-4519-ad85-4c9abf0be0b4)

 Although I had reinstalled the game, studio and plugins for many times, I couldn't solve this problem.
 I hope that I could get useful information, thanks!

**Comment by takahiro0327** [comment]
@hahaha12353 
Sorry if I misunderstood something.
I thought it was because you didn't press the [Transel Parallel] button.
![image](https://github.com/IllusionMods/KK_Plugins/assets/4230203/2e5bb6a2-fd92-4cd7-b3bc-1d3bbbd75a39)
![aaaaaa4](https://github.com/IllusionMods/KK_Plugins/assets/4230203/070f2b09-00d5-4d3a-ace6-c7b89339d783)

If so, please close the issues.

**Comment by hahaha12353** [comment]
![스니커즈](https://github.com/IllusionMods/KK_Plugins/assets/158009099/24bc6d4f-f859-4788-ac8c-376674dc1a24)
you're right... thanks a lot wow...
