### ISSUE TITLE
Headutl problem

### ISSUE THREAD

**Issue by ayson625** [DeathWeasel1337/KK_Plugins#43]
I put headutl mod with init in bepinex/ipa
But when I enter sex scene and push 0 on numpad nothing happened

**Comment by DeathWeasel1337** [comment]
Headutil has a long history of simply not working for some people. There are a few alternative POV plugins you can try:
PovX: https://github.com/FairBear/KK_PovX
RealPOV: https://github.com/Keelhauled/KeelPlugins

Since Headutil isn't my plugin there's not much I can do for you. If you have any problems you can visit the help channel of the Koikatsu Discord https://universalhentai.com/

**Comment by Fuscous1** [comment]
Same problem where almost all including the Keypad 3 is not working.
