### ISSUE TITLE
No VR subtitles

### ISSUE THREAD

**Issue by ethanccss** [DeathWeasel1337/KK_Plugins#48]
They work when played normally but in vr the subtitles aren't displayed (apparently they used to at some point? based on what I've read online). All it needs is for the text to display at the bottom of the headset! Thanks for your hard work.

**Comment by DeathWeasel1337** [comment]
I don't think it has ever displayed subtitles in VR, at least not by design. Displaying subtitles in VR is not quite as simple as it is to display them on screen, I've tried a couple times to get it to work without success. You have strange timing in posting this because I actually just started working on VR subtitles a few hours ago and managed to make it display text on the headset, so hopefully I can have VR subtitles done in a day or two.

**Comment by ethanccss** [comment]
What an awesome coincidence! I've talked to a number of people about this and they would be very interested as well. 
Thank you!

**Comment by DeathWeasel1337** [comment]
Subtitles v2.0 has subtitles for VR

**Comment by ethanccss** [comment]
Awesome Thank you! Testing now
